// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalasDeReunion.Models;

namespace SalasDeReunion.Migrations
{
    [DbContext(typeof(SalasDeReunionContext))]
    [Migration("20201109223722_AddCantidadDeGenteToReservas")]
    partial class AddCantidadDeGenteToReservas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalasDeReunion.Models.Reservas", b =>
                {
                    b.Property<int>("ReservasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadDeGente")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("ReservasId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SalasDeReunion.Models.Salas", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AccesoInet")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDeSala")
                        .HasColumnType("int");

                    b.Property<bool>("Pizarra")
                        .HasColumnType("bit");

                    b.Property<bool>("Proyector")
                        .HasColumnType("bit");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
